spring.application.name=AppointDoctor

#Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/appointDoctor
spring.datasource.username=root
spring.datasource.password=harsh@raj95
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

jwt.secret=UlQrQI9qmYCGN51ZtFJ8+hnK6yrYO+7a/x50BqZdj3E=

#Email Configuration
spring.mail.username=${MAIL_SERVICE_USERNAME}
spring.mail.password=${MAIL_SERVICE_PASS}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

#Thymleaf Configuration
spring.thymeleaf.cache=false


server.address=0.0.0.0
server.port=8080

socket.host= localhost
socket.port=8081

razorpay.key.id=rzp_test_F5nyEWUENPvtIw
razorpay.key.secret=A649tFFJDcfRuYvDk5YrF48A