package com.harsh.AppointDoctor.Services;

import com.harsh.AppointDoctor.Enums.AccountStatus;
import com.harsh.AppointDoctor.Enums.Days;
import com.harsh.AppointDoctor.Enums.SlotStatus;
import com.harsh.AppointDoctor.Models.AppointmentSlot;
import com.harsh.AppointDoctor.Models.DoctorOnboarding.Doctor;
import com.harsh.AppointDoctor.Models.DoctorOnboarding.DoctorClinicInfo;
import com.harsh.AppointDoctor.Models.DoctorOnboarding.OperationHours;
import com.harsh.AppointDoctor.Repo.AppointmentSlotRepo;
import com.harsh.AppointDoctor.Repo.DoctorOnboardingRepo.DoctorRepo;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;

@Service
@RequiredArgsConstructor
@Slf4j
public class SlotGenerationService {

    private final AppointmentSlotRepo slotRepo;
    private final DoctorRepo doctorRepo;

    /**
     * Generate slots for a doctor for next N days
     */
    @Transactional
    public void generateSlotsForDoctor(
            String doctorId,
            int daysAhead
    ) {
        Doctor doctor = doctorRepo.findById(doctorId)
                .orElseThrow(() -> new RuntimeException("Doctor not found"));

        DoctorClinicInfo clinicInfo = doctor.getClinicInfos();
        if (clinicInfo == null) {
            log.warn("No clinic info found for doctor {}", doctorId);
            return;
        }

        int consultationMinutes =
                Integer.parseInt(clinicInfo.getConsultationDuration());

        LocalDate today = LocalDate.now();

        for (int i = 0; i < daysAhead; i++) {
            LocalDate date = today.plusDays(i);
            generateSlotsForDate(
                    doctor,
                    clinicInfo,
                    date,
                    consultationMinutes
            );
        }
    }

    /**
     * Generate slots for a specific date
     */
    private void generateSlotsForDate(
            Doctor doctor,
            DoctorClinicInfo clinicInfo,
            LocalDate date,
            int consultationMinutes
    ) {
        DayOfWeek dayOfWeek = date.getDayOfWeek();

        for (OperationHours oh : clinicInfo.getOperatingHours()) {

            if (oh.getIsClosedToday() != null && oh.getIsClosedToday()) {
                continue;
            }

            if (!oh.getDays().name().equals(dayOfWeek.name())) {
                continue;
            }

            LocalTime start = LocalTime.parse(oh.getOpen());
            LocalTime end = LocalTime.parse(oh.getClose());

            while (!start.plusMinutes(consultationMinutes).isAfter(end)) {

                boolean exists = slotRepo.existsByDoctor_DoctorIdAndSlotDateAndSlotTime(
                        doctor.getDoctorId(), date, start
                );

                if (!exists) {
                    AppointmentSlot slot = new AppointmentSlot();
                    slot.setDoctor(doctor);
                    slot.setSlotDate(date);
                    slot.setSlotTime(start);
                    slot.setStatus(SlotStatus.AVAILABLE);

                    // slotId auto-generated by @PrePersist
                    slotRepo.save(slot);
                }

                start = start.plusMinutes(consultationMinutes);
            }
        }
    }

    @Transactional
    public void generateSlotsForAllDoctors() {

        List<Doctor> doctors =
                doctorRepo.findAll();

        LocalDate today = LocalDate.now();

        for (Doctor doctor : doctors) {
            try {
                generateSlotsForDoctor(doctor, today, 14);
            } catch (Exception e) {
                log.error("Slot generation failed for doctor {}",
                        doctor.getDoctorId(), e);
            }
        }
    }
    private void generateSlotsForDoctor(
            Doctor doctor,
            LocalDate startDate,
            int days
    ) {

        DoctorClinicInfo clinicInfo = doctor.getClinicInfos();
        if (clinicInfo == null) return;

        if (clinicInfo.getConsultationDuration() == null || clinicInfo.getConsultationDuration().isBlank()) {
            throw new IllegalArgumentException("Slot duration is missing");
        }

        int durationMinutes =
                Integer.parseInt(clinicInfo.getConsultationDuration());

        for (int i = 0; i < days; i++) {

            LocalDate date = startDate.plusDays(i);
            DayOfWeek dayOfWeek = date.getDayOfWeek();

            for (OperationHours oh : clinicInfo.getOperatingHours()) {

                if (Boolean.TRUE.equals(oh.getIsClosedToday())) continue;

                if (!oh.getDays().name().equals(dayOfWeek.name())) continue;

                LocalTime start = LocalTime.parse(oh.getOpen());
                LocalTime end = LocalTime.parse(oh.getClose());

                while (!start.plusMinutes(durationMinutes).isAfter(end)) {

                    boolean exists =
                            slotRepo.existsByDoctor_DoctorIdAndSlotDateAndSlotTime(
                                    doctor.getDoctorId(),
                                    date,
                                    start
                            );

                    if (!exists) {
                        AppointmentSlot slot = new AppointmentSlot();
                        slot.setDoctor(doctor);
                        slot.setSlotDate(date);
                        slot.setSlotTime(start);
                        slot.setStatus(SlotStatus.AVAILABLE);

                        slotRepo.save(slot); // slotId auto-generated
                    }

                    start = start.plusMinutes(durationMinutes);
                }
            }
        }
    }

}
